version: 2.1

orbs:
  docker: circleci/docker@2.0.1
  
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - docker/install-docker-compose:
          install-dir: /abc 
          version: latest 

workflows:
  example-workflow:
    jobs:
      - example-job